# Generated by Django 6.0.7 on 2026-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boliches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boliche',
            name='collector_id_mp',
        ),
        migrations.AddField(
            model_name='boliche',
            name='mp_access_token',
            field=models.TextField(blank=True, help_text='Access token del vendedor obtenido via OAuth MP', null=True),
        ),
        migrations.AddField(
            model_name='boliche',
            name='mp_connected_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el dueño conectó su cuenta MP', null=True),
        ),
        migrations.AddField(
            model_name='boliche',
            name='mp_refresh_token',
            field=models.TextField(blank=True, help_text='Refresh token para renovar el access token', null=True),
        ),
        migrations.AddField(
            model_name='boliche',
            name='mp_user_id',
            field=models.CharField(blank=True, help_text='ID del vendedor en MP (collector_id real)', max_length=100, null=True),
        ),
    ]
