# Generated by Django 6.0.7 on 2026-07-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boliches', '0002_remove_boliche_collector_id_mp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boliche',
            name='ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad donde se ubica el boliche', max_length=100),
        ),
    ]
