# Generated by Django 6.0.7 on 2026-07-21 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boliches', '0001_initial'),
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRRPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rrpp', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Asignación RRPP',
                'verbose_name_plural': 'Asignaciones RRPP',
            },
        ),
        migrations.CreateModel(
            name='LinkRRPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('lista', 'Lista'), ('venta_web', 'Venta Web')], max_length=20)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='rrpp.asignacionrrpp')),
            ],
            options={
                'verbose_name': 'Link RRPP',
                'verbose_name_plural': 'Links RRPP',
            },
        ),
        migrations.CreateModel(
            name='RRPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comision', models.CharField(choices=[('fijo', 'Monto fijo por ingresado'), ('porcentaje', 'Porcentaje del recaudado')], max_length=20)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boliche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rrpps', to='boliches.boliche')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_rrpp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RRPP',
                'verbose_name_plural': 'RRPPs',
            },
        ),
        migrations.AddField(
            model_name='asignacionrrpp',
            name='rrpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='rrpp.rrpp'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionrrpp',
            unique_together={('rrpp', 'evento')},
        ),
    ]
