# Generated by Django 6.0.7 on 2026-07-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boliches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('aforo_max', models.PositiveIntegerField()),
                ('color_pulsera', models.CharField(max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_up', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boliche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='boliches.boliche')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
    ]
