# Generated by Django 6.0.7 on 2026-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='habilitar_lista',
            field=models.BooleanField(default=True, help_text='Indica si el evento permite listas RRPP o solo venta anticipada web'),
        ),
    ]
