# Generated by Django 6.0.7 on 2026-07-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_organizador_standalone'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='genero',
            field=models.CharField(blank=True, default='', help_text='Género musical principal', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de imagen del evento', null=True),
        ),
    ]
