# Generated by Django 6.0.7 on 2026-07-21 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('rrpp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('tipo_ingreso', models.CharField(choices=[('web_anticipada', 'Compra Web'), ('lista_rrpp', 'Lista RRPP'), ('venta_general', 'Venta General')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado_guardia', 'Aprobado por Guardia'), ('rebotado_guardia', 'Rebotado por Guardia'), ('ingresado_final', 'Ingresado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('ya_pago_web', 'Ya pagó por web')], max_length=20, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wallet_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mp_fee_norware', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('ingresado_at', models.DateTimeField(blank=True, null=True)),
                ('rebotado_at', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistentes', to='eventos.evento')),
                ('link_rrpp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistentes', to='rrpp.linkrrpp')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'unique_together': {('evento', 'dni')},
            },
        ),
    ]
