# Generated by Django 6.0.7 on 2026-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puerta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='instagram',
            field=models.CharField(blank=True, default='', help_text='Username de Instagram del asistente', max_length=100),
        ),
    ]
